### ISSUE TITLE
Some fields are not updated

### ISSUE THREAD

**Issue by NL-Tristan** [akamming/domoticz-coronadashboard#5]
In general the plugin works fine in domoticz, only two fields are not updated.

total number of infectious people is always zero
and 
number of total contagious people per 100k inhabitants is also always zero.

All others fields (virtual sensors) are working and updated. I have installed the corona-plugin on two difference domoticz-servers, same problem.  
I like this plugin.

**Comment by akamming** [comment]
tx for reporting.

hmmm... I  indeed see they both stopped working last week. I just checked and the reason is the " last value"  field is no longer present in the [.json](https://coronadashboard.rijksoverheid.nl/json/NL.json) 

i think it is a bug on server side, cause i also see the normalized number of infectious people is also no longer present. and the " normal number of infectious people is about a week old.

I await a little while, see if it will be fixed server side. If not, i wil see if there is another way to parse into the sensor

**Comment by akamming** [comment]
Fixed both fields
